using System.Text.Json;

namespace ACCRPMMonitor;

// Handles loading and saving of per-vehicle RPM configs (both manual and auto)
// Directory structure: data/{car}/{track}/{car}_config.json or {car}_auto.json
// Reports and graphs also saved under: data/{car}/{track}/
public class ConfigMan
{
    private readonly string _configsDirectory;
    private string _currentVehicleName;
    private string _currentTrackName;
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true
    };

    public ConfigMode CurrentMode { get; private set; } = ConfigMode.Manual;

    public ConfigMan(string vehicleName = "default", string trackName = "default")
    {
        // Store configs in ./data directory next to the application
        string appDirectory = AppDomain.CurrentDomain.BaseDirectory;
        _configsDirectory = Path.Combine(appDirectory, "data");

        Directory.CreateDirectory(_configsDirectory);

        _currentVehicleName = SanitizeFileName(vehicleName);
        _currentTrackName = SanitizeFileName(trackName);
    }

    // Gets the vehicle+track-specific directory for generated files (reports, graphs, etc.)
    // Structure: data/{car}/{track}/
    public string GetVehicleDataDirectory()
    {
        string vehicleDir = Path.Combine(_configsDirectory, _currentVehicleName);
        string trackDir = Path.Combine(vehicleDir, _currentTrackName);
        Directory.CreateDirectory(trackDir);
        return trackDir;
    }

    // Sanitizes filenames to be filesystem-safe
    private static string SanitizeFileName(string name)
    {
        if (string.IsNullOrWhiteSpace(name))
            return "default";

        // Remove invalid path characters
        foreach (char c in Path.GetInvalidFileNameChars())
        {
            name = name.Replace(c, '_');
        }

        // Replace spaces and common special characters
        name = name.Replace(' ', '_').Replace('/', '_').Replace('\\', '_');

        // Convert to lowercase for consistency
        return name.ToLowerInvariant();
    }

    // Loads config from file based on current mode
    public GearRPMConfig LoadConfig()
    {
        string configFilePath = GetConfigPath(_currentVehicleName, CurrentMode);

        try
        {
            if (File.Exists(configFilePath))
            {
                string json = File.ReadAllText(configFilePath);
                var config = JsonSerializer.Deserialize<GearRPMConfig>(json);

                if (config != null)
                {
                    Console.WriteLine($"Configuration loaded from: {configFilePath}");
                    return config;
                }
            }

            // No config found - create default based on mode
            Console.WriteLine($"No configuration found. Creating default at: {configFilePath}");
            var defaultConfig = GearRPMConfig.CreateDefault();
            SaveConfig(defaultConfig);
            return defaultConfig;
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error loading configuration: {ex.Message}");
            Console.WriteLine("Using default configuration.");
            return GearRPMConfig.CreateDefault();
        }
    }

    // Saves config to file based on current mode
    public bool SaveConfig(GearRPMConfig config)
    {
        try
        {
            string configFilePath = GetConfigPath(_currentVehicleName, CurrentMode);
            string json = JsonSerializer.Serialize(config, JsonOptions);
            File.WriteAllText(configFilePath, json);
            Console.WriteLine($"Configuration saved to: {configFilePath}");
            return true;
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error saving configuration: {ex.Message}");
            return false;
        }
    }

    // Saves auto-generated config specifically
    public bool SaveAutoConfig(GearRPMConfig config)
    {
        try
        {
            string configFilePath = GetConfigPath(_currentVehicleName, ConfigMode.Auto);
            config.IsAutoGenerated = true;
            config.LastUpdated = DateTime.Now;
            string json = JsonSerializer.Serialize(config, JsonOptions);
            File.WriteAllText(configFilePath, json);
            Console.WriteLine($"Auto configuration saved to: {configFilePath}");
            return true;
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error saving auto configuration: {ex.Message}");
            return false;
        }
    }

    // Checks if auto config exists for current vehicle
    public bool HasAutoConfig()
    {
        return File.Exists(GetConfigPath(_currentVehicleName, ConfigMode.Auto));
    }

    // Sets the configuration mode
    public void SetMode(ConfigMode mode)
    {
        CurrentMode = mode;
    }

    public string ConfigFilePath => GetConfigPath(_currentVehicleName, CurrentMode);

    private string GetConfigPath(string vehicleName, ConfigMode mode)
    {
        // Structure: data/{car}/{track}/{car}_config.json or {car}_auto.json
        string vehicleDir = Path.Combine(_configsDirectory, vehicleName);
        string trackDir = Path.Combine(vehicleDir, _currentTrackName);
        Directory.CreateDirectory(trackDir);

        string suffix = mode == ConfigMode.Auto ? "_auto" : "_config";
        return Path.Combine(trackDir, $"{vehicleName}{suffix}.json");
    }

    public string CurrentVehicleName => _currentVehicleName;
    public string CurrentTrackName => _currentTrackName;

    public void SetVehicle(string vehicleName)
    {
        _currentVehicleName = SanitizeFileName(vehicleName);
    }

    public void SetTrack(string trackName)
    {
        _currentTrackName = SanitizeFileName(trackName);
    }

    public void SetVehicleAndTrack(string vehicleName, string trackName)
    {
        _currentVehicleName = SanitizeFileName(vehicleName);
        _currentTrackName = SanitizeFileName(trackName);
    }

    // Lists all available vehicle configs (scans data/{car}/ directories)
    public List<string> GetAvailableVehicles()
    {
        if (!Directory.Exists(_configsDirectory))
            return new List<string>();

        // Get all subdirectories under data/ (these are car names)
        var vehicleDirs = Directory.GetDirectories(_configsDirectory);
        var vehicles = new List<string>();

        foreach (var vehicleDir in vehicleDirs)
        {
            string vehicleName = Path.GetFileName(vehicleDir);
            if (!string.IsNullOrEmpty(vehicleName))
            {
                // Check if this vehicle has any track subdirectories with configs
                var trackDirs = Directory.GetDirectories(vehicleDir);
                if (trackDirs.Length > 0)
                {
                    vehicles.Add(vehicleName);
                }
            }
        }

        return vehicles.Distinct().OrderBy(n => n).ToList();
    }

    // Lists all available tracks for current vehicle
    public List<string> GetAvailableTracks()
    {
        string vehicleDir = Path.Combine(_configsDirectory, _currentVehicleName);
        if (!Directory.Exists(vehicleDir))
            return new List<string>();

        var tracks = Directory.GetDirectories(vehicleDir)
            .Select(d => Path.GetFileName(d))
            .Where(name => !string.IsNullOrEmpty(name))
            .OrderBy(n => n)
            .ToList();

        return tracks;
    }

    public bool DeleteVehicle(string vehicleName)
    {
        try
        {
            // Delete both manual and auto configs
            string manualPath = GetConfigPath(vehicleName, ConfigMode.Manual);
            string autoPath = GetConfigPath(vehicleName, ConfigMode.Auto);

            bool deleted = false;
            if (File.Exists(manualPath))
            {
                File.Delete(manualPath);
                deleted = true;
            }
            if (File.Exists(autoPath))
            {
                File.Delete(autoPath);
                deleted = true;
            }

            return deleted;
        }
        catch
        {
            return false;
        }
    }

    public bool VehicleExists(string vehicleName)
    {
        return File.Exists(GetConfigPath(vehicleName, ConfigMode.Manual));
    }
}

// Configuration mode enum
public enum ConfigMode
{
    Manual,  // User-defined RPM values
    Auto     // Auto-generated optimal values
}
