namespace ACCRPMMonitor;

/// <summary>
/// Report generated by PatternShift analyzer showing shift pattern analysis.
/// Used by Performance Learning Mode to correlate shift patterns with lap performance.
/// v3.7.1: Renamed from PerformanceReport to PerformanceReports for clarity.
/// Contains ShiftPatternReport and LearningReport data structures.
/// </summary>
public class ShiftPatternReport
{
    public int TotalShifts { get; set; }
    public int TotalLaps { get; set; }
    public int ValidLaps { get; set; }
    public int BestLapTime { get; set; }
    public int AverageLapTime { get; set; }
    public int TotalOffTrackEvents { get; set; }
    public DateTime GeneratedAt { get; set; }
    public List<GearShiftReport> GearReports { get; set; } = new();

    public string FormatLapTime(int milliseconds)
    {
        if (milliseconds == int.MaxValue)
            return "N/A";

        int totalSeconds = milliseconds / 1000;
        int minutes = totalSeconds / 60;
        int seconds = totalSeconds % 60;
        int ms = milliseconds % 1000;

        return $"{minutes}:{seconds:D2}.{ms:D3}";
    }
}

/// <summary>
/// Shift analysis for a specific gear.
/// </summary>
public class GearShiftReport
{
    public int Gear { get; set; }
    public int TotalShifts { get; set; }
    public int MinShiftRPM { get; set; }
    public int MaxShiftRPM { get; set; }
    public int AvgShiftRPM { get; set; }
    public int OptimalRPM { get; set; }
    public List<RPMBucketAnalysis> RPMBuckets { get; set; } = new();
}

/// <summary>
/// Performance analysis for shifts in a specific RPM bucket.
/// </summary>
public class RPMBucketAnalysis
{
    public int RPM { get; set; }
    public int ShiftCount { get; set; }
    public int AvgLapTime { get; set; }
    public double AvgOffTrackTime { get; set; }
    public double PerformanceScore { get; set; } // Lower is better
}

/// <summary>
/// Learning report generated by PerformanceEng showing physics vs performance comparison.
/// </summary>
public class LearningReport
{
    public DateTime GeneratedAt { get; set; }
    public float LearningRate { get; set; }
    public int TotalLaps { get; set; }
    public int ValidLaps { get; set; }
    public int TotalShifts { get; set; }
    public List<GearLearningReport> GearReports { get; set; } = new();
}

/// <summary>
/// Learning analysis for a specific gear comparing physics and performance data.
/// </summary>
public class GearLearningReport
{
    public int Gear { get; set; }
    public int? PhysicsBasedRPM { get; set; }
    public int? PerformanceBasedRPM { get; set; }
    public int? BlendedRPM { get; set; }
    public int Difference { get; set; } // Performance - Physics
    public string Interpretation { get; set; } = string.Empty;
}

/// <summary>
/// Monitoring session telemetry data report.
/// Generated when any monitoring mode stops to provide data insights.
/// </summary>
public class MonitoringSessionReport
{
    public DateTime SessionStart { get; set; }
    public DateTime SessionEnd { get; set; }
    public string VehicleName { get; set; } = "";
    public string TrackName { get; set; } = "";
    public string MonitoringMode { get; set; } = "";
    public int TotalDataPoints { get; set; }

    // Tire pressure data
    public List<TirePressureSnapshot> TirePressureData { get; set; } = new();
    public float AvgTirePressure { get; set; }
    public float MinTirePressure { get; set; }
    public float MaxTirePressure { get; set; }

    // Tire temperature data
    public List<TireTemperatureSnapshot> TireTemperatureData { get; set; } = new();
    public float AvgTireTemp { get; set; }
    public float MinTireTemp { get; set; }
    public float MaxTireTemp { get; set; }

    // RPM vs Time data
    public List<RPMSnapshot> RPMData { get; set; } = new();

    // Gear vs Time data
    public List<GearSnapshot> GearData { get; set; } = new();
    public Dictionary<int, int> GearTimeDistribution { get; set; } = new(); // Gear -> Total time in ms

    // Acceleration vs Gear
    public Dictionary<int, List<float>> AccelerationByGear { get; set; } = new(); // Gear -> List of speeds
    public Dictionary<int, AccelerationStats> GearAccelerationStats { get; set; } = new();
}

/// <summary>
/// Tire pressure snapshot at a specific time.
/// </summary>
public class TirePressureSnapshot
{
    public DateTime Timestamp { get; set; }
    public float FL { get; set; }
    public float FR { get; set; }
    public float RL { get; set; }
    public float RR { get; set; }
    public float Average { get; set; }
}

/// <summary>
/// Tire temperature snapshot at a specific time.
/// </summary>
public class TireTemperatureSnapshot
{
    public DateTime Timestamp { get; set; }
    public float FL { get; set; }
    public float FR { get; set; }
    public float RL { get; set; }
    public float RR { get; set; }
    public float Average { get; set; }
}

/// <summary>
/// RPM snapshot at a specific time.
/// </summary>
public class RPMSnapshot
{
    public DateTime Timestamp { get; set; }
    public int RPM { get; set; }
    public int Gear { get; set; }
}

/// <summary>
/// Gear snapshot at a specific time.
/// </summary>
public class GearSnapshot
{
    public DateTime Timestamp { get; set; }
    public int Gear { get; set; }
}

/// <summary>
/// Acceleration statistics for a specific gear.
/// </summary>
public class AccelerationStats
{
    public int Gear { get; set; }
    public float MinSpeed { get; set; }
    public float MaxSpeed { get; set; }
    public float AvgSpeed { get; set; }
    public int SampleCount { get; set; }
}
