namespace ACCRPMMonitor;

/// <summary>
/// Report generated by PatternShift analyzer showing shift pattern analysis.
/// Used by Performance Learning Mode to correlate shift patterns with lap performance.
/// </summary>
public class ShiftPatternReport
{
    public int TotalShifts { get; set; }
    public int TotalLaps { get; set; }
    public int ValidLaps { get; set; }
    public int BestLapTime { get; set; }
    public int AverageLapTime { get; set; }
    public int TotalOffTrackEvents { get; set; }
    public DateTime GeneratedAt { get; set; }
    public List<GearShiftReport> GearReports { get; set; } = new();

    public string FormatLapTime(int milliseconds)
    {
        if (milliseconds == int.MaxValue)
            return "N/A";

        int totalSeconds = milliseconds / 1000;
        int minutes = totalSeconds / 60;
        int seconds = totalSeconds % 60;
        int ms = milliseconds % 1000;

        return $"{minutes}:{seconds:D2}.{ms:D3}";
    }
}

/// <summary>
/// Shift analysis for a specific gear.
/// </summary>
public class GearShiftReport
{
    public int Gear { get; set; }
    public int TotalShifts { get; set; }
    public int MinShiftRPM { get; set; }
    public int MaxShiftRPM { get; set; }
    public int AvgShiftRPM { get; set; }
    public int OptimalRPM { get; set; }
    public List<RPMBucketAnalysis> RPMBuckets { get; set; } = new();
}

/// <summary>
/// Performance analysis for shifts in a specific RPM bucket.
/// </summary>
public class RPMBucketAnalysis
{
    public int RPM { get; set; }
    public int ShiftCount { get; set; }
    public int AvgLapTime { get; set; }
    public double AvgOffTrackTime { get; set; }
    public double PerformanceScore { get; set; } // Lower is better
}

/// <summary>
/// Learning report generated by PerformanceEng showing physics vs performance comparison.
/// </summary>
public class LearningReport
{
    public DateTime GeneratedAt { get; set; }
    public float LearningRate { get; set; }
    public int TotalLaps { get; set; }
    public int ValidLaps { get; set; }
    public int TotalShifts { get; set; }
    public List<GearLearningReport> GearReports { get; set; } = new();
}

/// <summary>
/// Learning analysis for a specific gear comparing physics and performance data.
/// </summary>
public class GearLearningReport
{
    public int Gear { get; set; }
    public int? PhysicsBasedRPM { get; set; }
    public int? PerformanceBasedRPM { get; set; }
    public int? BlendedRPM { get; set; }
    public int Difference { get; set; } // Performance - Physics
    public string Interpretation { get; set; } = string.Empty;
}
