namespace ACCRPMMonitor;

using ScottPlot;

// Generates visual power curve graphs for auto-generated configurations
public static class PwrCrvGraphGen
{
    /// <summary>
    /// Extracts user's average shift points from shift pattern report
    /// </summary>
    public static Dictionary<int, int> ExtractUserShiftPoints(ShiftPatternReport report)
    {
        var userShifts = new Dictionary<int, int>();

        foreach (var gearReport in report.GearReports)
        {
            if (gearReport.TotalShifts >= 5) // Need at least 5 shifts for reliable average
            {
                userShifts[gearReport.Gear] = gearReport.AvgShiftRPM;
            }
        }

        return userShifts;
    }

    // Generates a PNG image showing acceleration curves and gear ratios
    public static string GenerateGraph(GearRPMConfig config, string vehicleName, string outputDir, Dictionary<int, int>? userActualShiftPoints = null)
    {
        if (!config.IsAutoGenerated || config.AccelerationCurves.Count == 0)
        {
            throw new InvalidOperationException("Can only generate graphs for auto-generated configs with acceleration data");
        }

        // Ensure output directory exists
        Directory.CreateDirectory(outputDir);

        // Create the plot
        var plot = new Plot();

        // Configure plot appearance
        plot.Title($"{vehicleName} - Power Curve Analysis");
        plot.XLabel("RPM");
        plot.YLabel("Acceleration (m/s²)");
        plot.Legend.IsVisible = true;
        plot.Legend.Alignment = Alignment.LowerLeft;

        // Color palette for gears
        Color[] gearColors =
        {
            Colors.Red,
            Colors.Orange,
            Colors.Yellow,
            Colors.Green,
            Colors.Blue,
            Colors.Purple
        };

        // Only plot gears 1-6
        var gearsToPlot = config.AccelerationCurves
            .Where(kvp => kvp.Key >= 1 && kvp.Key <= 6)
            .OrderBy(kvp => kvp.Key)
            .ToList();

        if (gearsToPlot.Count == 0)
        {
            throw new InvalidOperationException("No acceleration data available for gears 1-6");
        }

        // Plot each gear's acceleration curve
        for (int i = 0; i < gearsToPlot.Count; i++)
        {
            var gear = gearsToPlot[i].Key;
            var accelData = gearsToPlot[i].Value;

            // Sort by RPM
            var sortedData = accelData.OrderBy(kvp => kvp.Key).ToList();

            double[] rpms = sortedData.Select(kvp => (double)kvp.Key).ToArray();
            double[] accels = sortedData.Select(kvp => (double)kvp.Value).ToArray();

            // Add scatter plot with lines for this gear
            var scatter = plot.Add.Scatter(rpms, accels);
            scatter.LegendText = $"Gear {gear}";
            scatter.Color = gearColors[i % gearColors.Length];
            scatter.LineWidth = 2;
            scatter.MarkerSize = 3;

            // Add optimal shift point marker (from physics/auto-config)
            if (config.GearRPMThresholds.TryGetValue(gear, out int optimalShiftRPM))
            {
                var closestRPM = accelData.Keys
                    .OrderBy(rpm => Math.Abs(rpm - optimalShiftRPM))
                    .FirstOrDefault();

                if (closestRPM > 0 && accelData.TryGetValue(closestRPM, out float shiftAccel))
                {
                    // Optimal shift marker (diamond)
                    var marker = plot.Add.Marker(optimalShiftRPM, shiftAccel);
                    marker.Color = gearColors[i % gearColors.Length];
                    marker.Size = 15;
                    marker.Shape = MarkerShape.FilledDiamond;

                    // Vertical dashed line
                    var vline = plot.Add.VerticalLine(optimalShiftRPM);
                    vline.Color = gearColors[i % gearColors.Length].WithAlpha(0.4);
                    vline.LineWidth = 2;
                    vline.LinePattern = LinePattern.Dashed;

                    // Label
                    var label = plot.Add.Text($"Optimal\n{optimalShiftRPM}", optimalShiftRPM, shiftAccel);
                    label.LabelFontSize = 9;
                    label.LabelFontColor = gearColors[i % gearColors.Length];
                    label.LabelBold = true;
                    label.OffsetY = 20;
                }
            }

            // Add user's actual average shift point (from pattern analyzer)
            if (userActualShiftPoints != null && userActualShiftPoints.TryGetValue(gear, out int actualShiftRPM))
            {
                var closestRPM = accelData.Keys
                    .OrderBy(rpm => Math.Abs(rpm - actualShiftRPM))
                    .FirstOrDefault();

                if (closestRPM > 0 && accelData.TryGetValue(closestRPM, out float actualAccel))
                {
                    // User actual shift marker (circle)
                    var marker = plot.Add.Marker(actualShiftRPM, actualAccel);
                    marker.Color = gearColors[i % gearColors.Length];
                    marker.Size = 12;
                    marker.Shape = MarkerShape.FilledCircle;

                    // Vertical dotted line
                    var vline = plot.Add.VerticalLine(actualShiftRPM);
                    vline.Color = gearColors[i % gearColors.Length].WithAlpha(0.3);
                    vline.LineWidth = 1.5f;
                    vline.LinePattern = LinePattern.Dotted;

                    // Label
                    var label = plot.Add.Text($"Actual\n{actualShiftRPM}", actualShiftRPM, actualAccel);
                    label.LabelFontSize = 8;
                    label.LabelFontColor = gearColors[i % gearColors.Length];
                    label.OffsetY = -20; // Below marker to avoid overlap
                }
            }
        }

        // Build info annotation with gear ratios and shift point legend
        string infoText = "";

        // Add gear ratios
        if (config.GearRatios.Count > 0)
        {
            infoText += "Gear Ratios:\n";
            foreach (var kvp in config.GearRatios.Where(g => g.Key >= 1 && g.Key <= 6).OrderBy(x => x.Key))
            {
                infoText += $"  {kvp.Key}→{kvp.Key + 1}: {kvp.Value:F3}\n";
            }
        }

        // Add shift point legend
        bool hasOptimal = config.GearRPMThresholds.Any(g => g.Key >= 1 && g.Key <= 6);
        bool hasActual = userActualShiftPoints != null && userActualShiftPoints.Any(g => g.Key >= 1 && g.Key <= 6);

        if (hasOptimal || hasActual)
        {
            if (infoText.Length > 0) infoText += "\n";
            infoText += "Shift Points:\n";

            if (hasOptimal)
                infoText += "  ◆ Optimal (Physics-based)\n";
            if (hasActual)
                infoText += "  ● Actual (User average)\n";
        }

        if (!string.IsNullOrEmpty(infoText))
        {
            var annotation = plot.Add.Annotation(infoText);
            annotation.LabelFontSize = 10;
            annotation.LabelBackgroundColor = Colors.White.WithAlpha(0.92);
            annotation.LabelBorderColor = Colors.Black;
            annotation.LabelBorderWidth = 1;
            annotation.OffsetX = 10;
            annotation.OffsetY = 10;
        }

        // Set reasonable axis limits
        plot.Axes.AutoScale();
        plot.Axes.Margins(0.05, 0.15); // Add some margin, especially on right for legend

        // Generate filename with timestamp
        string timestamp = DateTime.Now.ToString("yyyy-MM-dd_HH-mm-ss");
        string filename = $"{vehicleName}_PowerCurve_{timestamp}.png";
        string fullPath = Path.Combine(outputDir, filename);

        // Save the plot as PNG (1920x1080 for good quality)
        plot.SavePng(fullPath, 1920, 1080);

        return fullPath;
    }

    // Alternative method to generate a simpler graph without optimal shift markers
    public static string GenerateSimpleGraph(Dictionary<int, Dictionary<int, float>> accelerationCurves,
                                             Dictionary<int, float> gearRatios,
                                             string vehicleName,
                                             string outputDir)
    {
        // Ensure output directory exists
        Directory.CreateDirectory(outputDir);

        // Create the plot
        var plot = new Plot();

        // Configure plot appearance
        plot.Title($"{vehicleName} - Acceleration Curves");
        plot.XLabel("RPM");
        plot.YLabel("Acceleration (m/s²)");
        plot.Legend.IsVisible = true;
        plot.Legend.Alignment = Alignment.LowerLeft;

        // Color palette for gears
        Color[] gearColors =
        {
            Colors.Red,
            Colors.Orange,
            Colors.Yellow,
            Colors.Green,
            Colors.Blue,
            Colors.Purple
        };

        // Only plot gears 1-6
        var gearsToPlot = accelerationCurves
            .Where(kvp => kvp.Key >= 1 && kvp.Key <= 6)
            .OrderBy(kvp => kvp.Key)
            .ToList();

        // Plot each gear's acceleration curve
        for (int i = 0; i < gearsToPlot.Count; i++)
        {
            var gear = gearsToPlot[i].Key;
            var accelData = gearsToPlot[i].Value;

            // Sort by RPM
            var sortedData = accelData.OrderBy(kvp => kvp.Key).ToList();

            double[] rpms = sortedData.Select(kvp => (double)kvp.Key).ToArray();
            double[] accels = sortedData.Select(kvp => (double)kvp.Value).ToArray();

            // Add scatter plot with lines for this gear
            var scatter = plot.Add.Scatter(rpms, accels);
            scatter.LegendText = $"Gear {gear}";
            scatter.Color = gearColors[i % gearColors.Length];
            scatter.LineWidth = 2;
            scatter.MarkerSize = 3;
        }

        // Add gear ratio information
        if (gearRatios.Count > 0)
        {
            var ratioText = "Gear Ratios:\n";
            foreach (var kvp in gearRatios.Where(g => g.Key >= 1 && g.Key <= 6).OrderBy(x => x.Key))
            {
                ratioText += $"  {kvp.Key}→{kvp.Key + 1}: {kvp.Value:F3}\n";
            }

            var annotation = plot.Add.Annotation(ratioText);
            annotation.LabelFontSize = 11;
            annotation.LabelBackgroundColor = Colors.White.WithAlpha(0.9);
            annotation.LabelBorderColor = Colors.Black;
            annotation.LabelBorderWidth = 1;
            annotation.OffsetX = 10;
            annotation.OffsetY = 10;
        }

        // Set reasonable axis limits
        plot.Axes.AutoScale();
        plot.Axes.Margins(0.05, 0.15);

        // Generate filename with timestamp
        string timestamp = DateTime.Now.ToString("yyyy-MM-dd_HH-mm-ss");
        string filename = $"{vehicleName}_PowerCurve_{timestamp}.png";
        string fullPath = Path.Combine(outputDir, filename);

        // Save the plot
        plot.SavePng(fullPath, 1920, 1080);

        return fullPath;
    }
}
